This code contains only exploratory data analysis to prepare the necessary data for my masterthesis on the topic of "ML in portfolio optimization context". In the beginning of March I send Prof. Haas Version1 of my EDA, where he claimed several drawbacks. Therefore, we decided to move on with sector data from the STOXX Europe 600.

In [1]:
import pandas as pd

In [2]:
data = pd.read_excel('00_STOXXEurope_Indizes.xlsx', index_col=0, parse_dates=True)
data.head()

,STOXX EUROPE 600 \nE - PRICE INDEX,STOXX EUROPE 600 \nBANKS E - PRICE INDEX,STOXX EUROPE 600 \nFINANCIALS E - PRICE INDEX,STOXX EUROPE 600 \nAUTO & PARTS E - PRICE INDEX,STOXX EUROPE 600 \nENERGY E - PRICE INDEX,STOXX EUROPE 600 \nINSURANCE E - PRICE INDEX,STOXX EUROPE 600 \nREAL ESTATE E - PRICE INDEX,STOXX EUROPE 600 \nTECHNOLOGY E - PRICE INDEX,STOXX EUROPE 600 \nUTILITIES E - PRICE INDEX,STOXX EUROPE 600 \nCHEMICALS E - PRICE INDEX,STOXX EUROPE 600 \nBASIC RESOURCE E - PRICE INDEX,STOXX EUROPE 600 \nCON & MAT E - PRICE INDEX,STOXX EUROPE 600\n FOOD BEV TOB E - PRICE INDEX,STOXX EUROPE 600 \nHEALTH CARE E - PRICE INDEX,STOXX EUROPE 600 \nINDS GDS & SVS E - PRICE INDEX,STOXX EUROPE 600 \nMEDIA E - PRICE INDEX,STOXX EUROPE 600 \nCONS PRD&SVS E - PRICE INDEX,STOXX EUROPE 600 \nRETAIL E - PRICE INDEX,STOXX EUROPE 600 \nTRAVEL & LEIS E - PRICE INDEX,STOXX EUROPE 600 \nTELECOM E - PRICE INDEX
1986-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1986-02-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1986-03-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1986-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1986-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data.rename(columns={'STOXX EUROPE 600 \nE - PRICE INDEX': 'STOXX Europe 600', 
                     'STOXX EUROPE 600 \nBANKS E - PRICE INDEX': 'Banks',
                     'STOXX EUROPE 600 \nFINANCIALS E - PRICE INDEX': 'Financials',
                     'STOXX EUROPE 600 \nAUTO & PARTS E - PRICE INDEX': 'Auto & Parts',
                     'STOXX EUROPE 600 \nENERGY E - PRICE INDEX': 'Energy',
                     'STOXX EUROPE 600 \nINSURANCE E - PRICE INDEX': 'Insurance',
                     'STOXX EUROPE 600 \nREAL ESTATE E - PRICE INDEX': 'Real Estate',
                     'STOXX EUROPE 600 \nTECHNOLOGY E - PRICE INDEX': 'Technology',
                     'STOXX EUROPE 600 \nUTILITIES E - PRICE INDEX': 'Utilities',
                     'STOXX EUROPE 600 \nCHEMICALS E - PRICE INDEX': 'Chemicals',
                     'STOXX EUROPE 600 \nBASIC RESOURCE E - PRICE INDEX': 'Basic Resource',
                     'STOXX EUROPE 600 \nCON & MAT E - PRICE INDEX': 'Con & Mat',
                     'STOXX EUROPE 600\n FOOD BEV TOB E - PRICE INDEX': 'Food Bev',
                     'STOXX EUROPE 600 \nHEALTH CARE E - PRICE INDEX': 'Health Care',
                     'STOXX EUROPE 600 \nINDS GDS & SVS E - PRICE INDEX': 'Inds Gds & Svs', 
                     'STOXX EUROPE 600 \nMEDIA E - PRICE INDEX': 'Media',
                     'STOXX EUROPE 600 \nCONS PRD&SVS E - PRICE INDEX': 'Cons Prd & Svs',
                     'STOXX EUROPE 600 \nRETAIL E - PRICE INDEX': 'Retail',
                     'STOXX EUROPE 600 \nTRAVEL & LEIS E - PRICE INDEX': 'Travel & Leisure',
                     'STOXX EUROPE 600 \nTELECOM E - PRICE INDEX': 'Telecoms'}, inplace=True)
data.tail()

,STOXX Europe 600,Banks,Financials,Auto & Parts,Energy,Insurance,Real Estate,Technology,Utilities,Chemicals,Basic Resource,Con & Mat,Food Bev,Health Care,Inds Gds & Svs,Media,Cons Prd & Svs,Retail,Travel & Leisure,Telecoms
2022-08-01,437.464,127.997,199.409,546.198,108.391,290.063,150.294,622.670,377.678,1161.506,583.656,524.670,227.088,1049.096,659.795,342.336,379.859,316.474,187.424,227.973
2022-09-01,407.656,122.762,190.352,510.098,111.525,286.282,130.066,550.458,354.627,1082.200,551.018,489.394,217.062,965.835,592.733,307.082,343.418,271.831,179.498,218.502
2022-10-01,390.828,119.954,184.429,480.511,108.329,275.423,112.112,525.917,331.380,1065.746,563.096,465.986,205.692,936.413,568.604,302.951,323.159,252.950,171.653,197.229
2022-11-01,414.610,129.938,197.814,524.474,118.941,296.449,118.717,552.749,344.071,1140.962,582.272,501.354,209.419,980.350,626.628,322.018,334.965,272.531,200.185,200.203
2022-12-01,443.965,138.911,213.153,561.266,122.007,323.004,121.319,640.507,373.472,1203.192,649.966,536.327,219.764,1025.381,669.064,344.206,378.472,307.895,212.083,204.210

As we can see from data.head(), the first rows of data are NaN. Therefore we skip the first year and start the EDA at 1987.

In [4]:
# values from 01-01-1987 until 01-12-20222
price_data = data[12:]

In [5]:
price_data.tail()

,STOXX Europe 600,Banks,Financials,Auto & Parts,Energy,Insurance,Real Estate,Technology,Utilities,Chemicals,Basic Resource,Con & Mat,Food Bev,Health Care,Inds Gds & Svs,Media,Cons Prd & Svs,Retail,Travel & Leisure,Telecoms
2022-08-01,437.464,127.997,199.409,546.198,108.391,290.063,150.294,622.670,377.678,1161.506,583.656,524.670,227.088,1049.096,659.795,342.336,379.859,316.474,187.424,227.973
2022-09-01,407.656,122.762,190.352,510.098,111.525,286.282,130.066,550.458,354.627,1082.200,551.018,489.394,217.062,965.835,592.733,307.082,343.418,271.831,179.498,218.502
2022-10-01,390.828,119.954,184.429,480.511,108.329,275.423,112.112,525.917,331.380,1065.746,563.096,465.986,205.692,936.413,568.604,302.951,323.159,252.950,171.653,197.229
2022-11-01,414.610,129.938,197.814,524.474,118.941,296.449,118.717,552.749,344.071,1140.962,582.272,501.354,209.419,980.350,626.628,322.018,334.965,272.531,200.185,200.203
2022-12-01,443.965,138.911,213.153,561.266,122.007,323.004,121.319,640.507,373.472,1203.192,649.966,536.327,219.764,1025.381,669.064,344.206,378.472,307.895,212.083,204.210

In [6]:
# Calculate the number of non-null values in each column
num_non_null = price_data.count()

# Find the columns with less than 432 non-null values
less_than_432 = num_non_null[num_non_null < 432]
more_than_432 = num_non_null[num_non_null >= 432]

# Print the column names
print(list(less_than_432.index))

['Energy', 'Real Estate', 'Food Bev', 'Cons Prd & Svs', 'Retail', 'Travel & Leisure']

Column with less than 432 non-null values (36 years):

1. Energy
2. Real Estate
3. Food Bev
4. Cons Prd & Svs
5. Retail
6. Travel & Leisure

In [7]:
# Calculate the number of non-null values in each column
num_non_null = price_data.count()

# Find the columns with less than 432 non-null values
less_than_300 = num_non_null[num_non_null < 300]

# Print the column names
print(list(less_than_300.index))

['Energy', 'Real Estate', 'Food Bev', 'Cons Prd & Svs']

Values with less than 300 non-null values (25 years):

1. Energy
2. Real Estate
3. Food Bev
4. Cons Prd & Svs

So either we could work with a full data set of 35 years including the STOXX Europe 600 as a benchmark and 13 out of 19 sector indices  OR a full data set of 25 years including the STOXX Europe 600 as a benchmark and 15 out of 19 sector indices.

After a discussion with my professor we decised to work with the data set of 36 years.

In [8]:
# save table as csv file
# agreement with Prof. Dr. Markus Haas on 36 years

data_filter = price_data.loc['1987-01-01':'2022-01-01']
data_filter = data_filter[list(more_than_432.index)]
data_filter.head()

,STOXX Europe 600,Banks,Financials,Auto & Parts,Insurance,Technology,Utilities,Chemicals,Basic Resource,Con & Mat,Health Care,Inds Gds & Svs,Media,Telecoms
1987-01-01,82.76,103.62,108.12,166.13,110.29,112.06,66.19,94.91,72.03,83.28,42.90,80.86,71.48,67.89
1987-02-01,83.03,102.08,105.84,148.67,105.48,106.04,66.08,94.13,72.67,90.01,47.49,82.46,77.74,68.03
1987-03-01,86.22,98.86,104.25,144.40,105.30,108.33,67.77,98.81,75.40,96.46,54.20,90.17,83.26,72.75
1987-04-01,88.66,99.99,106.46,151.33,108.12,115.18,67.90,102.82,80.26,97.76,53.05,90.53,85.47,72.04
1987-05-01,91.14,99.01,106.76,154.33,108.50,118.75,68.42,102.98,85.58,102.03,54.31,93.53,86.86,80.77

In [9]:
data_filter.to_csv('data/price_data_filtered.csv')

In [10]:
# show the total number of values
data_filter.index.size

421